// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuvruLpcEZKKep7g3-efzUFN9H_XbgBw',
    appId: '1:686102221973:web:6acb1c96416fc6cdd9b79c',
    messagingSenderId: '686102221973',
    projectId: 'clearance-app-e89dc',
    authDomain: 'clearance-app-e89dc.firebaseapp.com',
    storageBucket: 'clearance-app-e89dc.appspot.com',
    measurementId: 'G-QHBFE3K3ZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiiFVwbDBcviC-DOjSFcZRCUCpjdliwbU',
    appId: '1:686102221973:android:3aaec9bca6922768d9b79c',
    messagingSenderId: '686102221973',
    projectId: 'clearance-app-e89dc',
    storageBucket: 'clearance-app-e89dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgkiapNzVA88TZKirGSbceCOW3fAl1VI',
    appId: '1:686102221973:ios:3e9fb16d0ca116a7d9b79c',
    messagingSenderId: '686102221973',
    projectId: 'clearance-app-e89dc',
    storageBucket: 'clearance-app-e89dc.appspot.com',
    iosBundleId: 'com.example.clearanceApp',
  );
}
